- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/IRestRequest.cs
- Snowflake.Data/Core/RestRequestImpl.cs
- Snowflake.Data/Core/RestResponse.cs
- Snowflake.Data/Core/SFChunkDownloader.cs
- Snowflake.Data/Core/SFDataConverter.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Core/SFStatement.cs
Currently, sessions can not be renewed as the response for these is not handled correctly. The response is currently cast to a NullDataResponse, which fails and throws an exception due to the data field being an object not a string. I created a new response class and applied it to the response. I also made the session object reflect the change in token generated by snowflake.
There is also a minor change to fix logging index error.
Fixes issue #16
> Fixing renewal of sessions

- Snowflake.Data/Client/SnowflakeDbParameter.cs
This PR proposes a fix for #54 by relaxing behavior of the getters and setters in `SnowflakeDbParameter`.   
This isn't an urgent change, but ultimately we'd prefer not to maintain a fork.
> Remove `NotImplementedExceptions` from `SnowflakeDbParameter` properties.`

- Snowflake.Data/Core/HttpUtil.cs
This came from our fork of the connector. I cannot actually remember now what the specific error was that was transient and retry-able. 
Some exploration would probably be good as to what errors could be transient. A max retries in this section also might be beneficial.
> Transient Errors during Http requests are not retried

- Snowflake.Data.Tests/SFDbDataReaderIT.cs
> Fix SFDbDataReaderIT.testGetDateTime on time zones ahead of UTC

- Snowflake.Data.Tests/Mock/MockRestSessionExpired.cs
- Snowflake.Data.Tests/Mock/MockRestSessionExpiredInQueryExec.cs
- Snowflake.Data.Tests/Mock/MockServiceName.cs
- Snowflake.Data.Tests/SFStatementTest.cs
- Snowflake.Data/Core/IRestRequest.cs
- Snowflake.Data/Core/RestRequestImpl.cs
- Snowflake.Data/Core/SFBlockingChunkDownloader.cs
- Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
- Snowflake.Data/Core/SFChunkDownloaderV2.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Core/SFSessionParameter.cs
- Snowflake.Data/Core/SFStatement.cs
This PR contains two commits:
1. Refactor RestRequest with: 1) changing its name to RestRequester; 2) Remove all logics of RestRequest from the requester to request (inversion of control), since RestRequester should know nothing about RestRequest.
2. Add SERVICE_NAME support so that it can read SERVICE_NAME parameter from the payload and send out the next request with a service name in the header.
> Add SERVICE_NAME support to .NET

- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFDbTransactionIT.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbTransaction.cs
This PR is to resolve #20 and #64 
There are four classed that implements IDisposable interface:
1. Connection
2. Transaction
3. Command
4. DataReader
I only implemented Dispose() function for connection and transaction. The dispose would call close() and rollback() respectably.
Our Command and DataReader does not hold any resources so there is not need to override the Dispose() on them.
> Implement Dispose for Connection and Transaction.

- Snowflake.Data.Tests/SFDbDataReaderIT.cs
- Snowflake.Data/Client/SnowflakeDbCommand.cs
- Snowflake.Data/Client/SnowflakeDbDataReader.cs
- Snowflake.Data/Core/ResultSetUtil.cs
- Snowflake.Data/Core/SFResultSet.cs
Customers using ASP.NET EntityFramework would have exception because in the framework's codebase, the RecordsAffected property would be called even if the the reader is closed. See https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Storage/RelationalDataReader.cs#L115
This PR is to fetch RowsAffected earlier for dataReader.
> SNOW-76790 .Net dbDataReader RowsAffected issue

- Snowflake.Data.Tests/Mock/MockCloseSessionGone.cs
- Snowflake.Data.Tests/Mock/MockOkta.cs
- Snowflake.Data.Tests/Mock/MockRestSessionExpired.cs
- Snowflake.Data.Tests/Mock/MockRestSessionExpiredInQueryExec.cs
- Snowflake.Data.Tests/Mock/MockServiceName.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data/Core/Authenticator/BasicAuthenticator.cs
- Snowflake.Data/Core/Authenticator/IAuthenticator.cs
- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/SFSession.cs
This is a fix to address #138 
Have separate code routine to do sync authentication;
Using threadpool for execution.
> Fix Okta authentication Deadlock issue 

- Snowflake.Data/Client/SnowflakeDbParameter.cs
This could unblock potential use case from frameworks such as EntityFrameworkCore.
[SqlServer .NET driver](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlparameter.value?view=netframework-4.8)  just pass through these properties.
> SNOW-81118 Not being strict on some properties for DBParameter 

- README.md
- Snowflake.Data.Tests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/SFSessionProperty.cs
It would remove the connection group and the region name.
I did not change any document because the scope for the statement "hostname field is going to be deprecated" in [JIRA](https://snowflakecomputing.atlassian.net/browse/SNOW-76706). In that JIRA SnowSQL is going to be deprecate hostname, but not mentioning other drivers.
@smtakeda @notkriswagner Do we want every driver to follow that SnowSQL and deprecate hostname, using only account to specify the account, region and connection group?
If yes then I will change the document accordingly, otherwise I would not modify the document since we already encourage the customers to use hostname rather than account to form URL in our docs.
> @SNOW-81851 add filter to ACCOUNT 

- Snowflake.Data.Tests/DedicatedThreadSynchronisationContext.cs
- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/SFDbCommandIT.cs
- Snowflake.Data/Client/SnowflakeDbCommand.cs
- Snowflake.Data/Core/Authenticator/BasicAuthenticator.cs
- Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs
- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/SFBlockingChunkDownloader.cs
- Snowflake.Data/Core/SFDataConverter.cs
- Snowflake.Data/Core/SFResultSet.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Core/SFStatement.cs
This fixes issue #153 by adding ConfigureAwait(false) to all await points in the library.
It also modifies the unit tests so any future problems like this will cause unit tests to fail.
> Fix for #153

- Snowflake.Data.Tests/SFDbCommandIT.cs
- Snowflake.Data/Client/SnowflakeDbCommand.cs
I delayed the creation of SfStatement until it's needed: when executing a command. Behavior does not change with this implementation. All tests pass and I added a new test to test for the issue this fix addresses.
> Create SfStatement when executing DbCommand #180

- Snowflake.Data.Tests/Mock/MockRestSessionExpired.cs
- Snowflake.Data.Tests/SFStatementTest.cs
- Snowflake.Data/Core/SFStatement.cs
Session expire does not infer that request is not reached to the system. In such case we need to keep the request ID to be the same.
> SNOW-92881 Consistent RequestID

- .github/workflows/main.yml
This will add a button for build-test workflow to run it manually . This will be useful for Releng team to run .Net tests on master or any other branch as part of pre-release of server release is done to ensure it does not break .Net connector
> SNOW-208979 Add option to trigger Github Action Build/Test manually

- Snowflake.Data/Client/SnowflakeDbCommand.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/SFStatement.cs
Calling cancel on a query should not generate an exception when it fails: https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand.cancel?view=net-5.0
This fixes the issue by logging the failed cancellation as a warning instead of throwing an exception.
Note: a different exception is still thrown since the command failed to execute. And is bubbled up to SnowflakeDbCommand for visibility
> Log query cancellation failure as a warning

- .github/workflows/main.yml
- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data/Core/SFSessionProperty.cs
**For the Setup Nuget.exe error "The `add-path` command is disabled"**
Most likely started to fail because of https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/, but since the actions are retired, I changed to the official ones. It fixed the error.
https://github.com/warrenbuckley/Setup-Nuget : This GitHub action is now retired/archived as I have collobrated directly with Microsoft to release an official MSBuild GitHub Action https://github.com/NuGet/setup-nuget
https://github.com/warrenbuckley/Setup-MSBuild : This GitHub action is now retired/archived as I have collobrated directly with Microsoft to release an official MSBuild GitHub Action https://github.com/microsoft/setup-msbuild
**For the error NU1101: Unable to find package XX**
Added …
> Fixing failing Build GitHub actions

- Snowflake.Data.Tests/SFDataConverterTest.cs
- Snowflake.Data.Tests/SFReusableChunkTest.cs
- Snowflake.Data/Core/FastMemoryStream.cs
- Snowflake.Data/Core/FastParser.cs
- Snowflake.Data/Core/IResultChunk.cs
- Snowflake.Data/Core/ReusableChunkParser.cs
- Snowflake.Data/Core/SFBaseResultSet.cs
- Snowflake.Data/Core/SFDataConverter.cs
- Snowflake.Data/Core/SFResultChunk.cs
- Snowflake.Data/Core/SFResultSet.cs
- Snowflake.Data/Core/SFReusableChunk.cs
- Snowflake.Data/Core/UTF8Buffer.cs
* Uses handwritten parsers for integers and decimals
* Keeps data in UTF8 format until we absolutely need to convert it to strings
In a testcase that downloads 266 million rows we had the following runtime before this change:
.Net Framework 00:13:16
Core           00:05:16
After this change the same testcase has the following runtime:
.Net Framework 00:02:18
Core           00:02:29
> SNOW-344502 - Improved performance when downloading large amounts of data.

- Snowflake.Data/Core/SFSessionProperty.cs
Current connector is processing "Authenticator" setting values using case sensitive comparison. This is an issue because when using authenticator=SNOWFLAKE_JWT for example, the connector does not identify the authentication mechanism as JWT and falls back to the default Snowflake authentication mechanism with username and password. It then fail because the password is not provided.
With this change, it validates the required connection string properties using case insensitive comparison.
> SNOW-344228 - Case insensitive authenticator settings comparison

- Snowflake.Data.Tests/SFDataConverterTest.cs
- Snowflake.Data/Core/FastParser.cs
For values v in -1<{v}<0, the sign was lost and for example -0.99 would be converted to 0.99. This was because 0 doesn't really has a sign and the conversion was splitting up the raw data in 2 parts : int part and decimal part. Loosing the sign.
> SNOW-344502 - Fix conversion issue for decimal negative value between -1 and 0

- Snowflake.Data/Core/RestRequester.cs
This is a long standing issue, I am looking to reopen it as it seems like this repository is getting a bit more focus in the recent timeframe.
Original PRs:
* https://github.com/snowflakedb/snowflake-connector-net/pull/161
* https://github.com/snowflakedb/snowflake-connector-net/pull/163
I and @tdg5 have an internal fork of this library because we require the streaming behavior and our apps run on `netcoreapp3.1` and/or `net5.0`.  We've been using them with this change for quite some time and it seems to work well. I am hoping the [previous problem with Azure automated tests](https://github.com/snowflakedb/snowflake-connector-net/pull/161#issuecomment-523207912) isn't a problem anymore, we'll see when the checks for this PR get run. We'd love to just rely on the official fork, with some …
> allow for http streaming on all frameworks, not just `NETFRAMEWORK`

- Snowflake.Data.Tests/SFDataConverterTest.cs
- Snowflake.Data/Core/FastParser.cs
- Snowflake.Data/Core/SFDataConverter.cs
- Snowflake.Data/Core/UTF8Buffer.cs
If either the "integer" or fractional part was greater than max int64, the conversion would fail with an overflow error.
The driver now falls back to using the generic decimal.Parse in these cases to prevent incorrect overflow error.
Note that Snowflake numeric can still cause overflow when converted to C# decimal because the C# decimal range is 29 while Snowflake numeric is 38.
> SNOW-219780 - Decimal conversion overflow issue

- README.md
- Snowflake.Data.Tests/Mock/MockRetryUntilRestTimeout.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/Authenticator/IAuthenticator.cs
- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
- Snowflake.Data/Core/ChunkDownloaderFactory.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestRequest.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/SFBlockingChunkDownloader.cs
- Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
- Snowflake.Data/Core/SFChunkDownloaderV2.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Core/SFSessionProperty.cs
- Snowflake.Data/Core/SFStatement.cs
Adding a new connection setting to allow users to turn off Certificate Revocation List validation if/when needed.
> SNOW-363754 - Ability to turn off Certificate Revocation List validation

- Snowflake.Data/Core/SFStatement.cs
Similar to https://github.com/snowflakedb/snowflake-connector-net/pull/296, I ran into the following issue. If for some reason the Cancel request throws an exception when being called by the CancellationToken Register delegate, then it results in an Unhandled Exception that crashes the process. To prevent that issue from occurring, I'm just wrapping this one spot in a Try/Catch with a log message if an exception is caught.
Example of the error from the Event Viewer:
```
instance of Win32_NTLogEvent
{
Computer = "XXXXX";
EventCode = 1026;
EventIdentifier = 1026;
Logfile = "Application";
RecordNumber = 145917;
SourceName = ".NET Runtime";
TimeGenerated = "20210518150523.000000-000";
TimeWritten = "20210518150523.000000-000";
Type = "Error";
EventType = 1;
Category = 0;
CategoryString = …
```
> Prevent unhandled exception when calling Cancel

- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/SFStatement.cs
`CancellationTokenSource` implements `IDisposable` so should be disposed. My experience suggests that these do get GC'd eventually as it currently stands, but it seems like explicit handling is more desirable.
> Better dispose of CancellationTokenSources

- README.md
- Snowflake.Data/Core/SFSessionProperty.cs
Adding the capability for the user to provide the full account name directly in the Account setting instead of having to provide it via the Host setting in conjunction with the Account setting as done before.
For example, if the previous connection string was : 
`host={accountVal}.{region}.{cloudPlatform}.snowflakecomputing.com;authenticator=externalbrowser;user=xxx;account={accountVal}`
The new connection string is : 
`account={accountVal}.{region}.{cloudPlatform};authenticator=externalbrowser;user=xxx`
> Supports using full account name with region and cloud platform

- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestRequester.cs
Since SecretDetector is in place, add the logging that was removed in https://github.com/snowflakedb/snowflake-connector-net/pull/188/
> Re-add Http message logging

- README.md
Sorted the table and added a new DISABLERETRY row for the new connection setting.
DISABLERETRY   N.  Disables the driver from automatically reconnecting when a connection fails or drops. Default: false.
> SNOW-592041-disable-retry

- Snowflake.Data/Core/Authenticator/KeyPairAuthenticator.cs
Follow up PR for https://github.com/snowflakedb/snowflake-connector-net/pull/459
Based off https://github.com/snowflakedb/snowflake-connector-net/pull/452
Added the missing exception for key pair
> Refactor the exception thrown for incorrect private key

- Snowflake.Data.Tests/SFConnectionPoolT.cs
- Snowflake.Data.Tests/SFPutGetTest.cs
put get test case start to hang on AWS+Windows+.net472 on github. It doesn't seem to related to recent changes and can't be reproduced locally. Ignore it for now until we find the root cause.
> Ignore hanging test for now

- Snowflake.Data.Tests/HttpUtilTest.cs
- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
- Snowflake.Data/Core/HttpUtil.cs
Based on SF# 00373675
Refactored the isRetryableHTTPCode() function outside of the RetryHandler class to allow testing
> Add unit test for isRetryableHTTPCode() function

- Snowflake.Data.Tests/SFPutGetTest.cs
- Snowflake.Data/Core/FileTransfer/EncryptionProvider.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFRemoteStorageUtil.cs
- Snowflake.Data/Core/RestResponse.cs
Fix issue where block is not flushed after decrypted stream causing the downloaded file to be incomplete
> Flush block after copying decrypted stream

- Snowflake.Data/Core/FileTransfer/SFFileMetadata.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFRemoteStorageUtil.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Snowflake.Data/Core/RestResponse.cs
- Snowflake.Data/Core/SFStatement.cs
PUT refactoring + adding proxy for S3 client:
- PUT/GET command is now case insensitive
- Trim white spaces in beginning and end of queries
- Allow white spaces in file paths for PUT queries
- Update the response data when client is renewed
- Move retry logic for when client is renewed and/or presigned url is updated
PR for error handling: https://github.com/snowflakedb/snowflake-connector-net/pull/501
PR to use async/await : https://github.com/snowflakedb/snowflake-connector-net/pull/510
The PR to remove the cloud dependencies SDK and use the REST API is in progress
> PUT command refactors + proxy for S3 client

- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
Based off SF# 00402205
Set System.Text.RegularExpressions to 4.3.1 to resolve snyk vulnerability: http://security.snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTREGULAREXPRESSIONS-174708
> Set System.Text.RegularExpressions to 4.3.1

- Snowflake.Data/Snowflake.Data.csproj
reduce one version number at csproj file, we have version and AssemblyVersion on csproj file, after this fix, we only have to update version on csproj, AssemblyVersion will use the same version number automatically.
> reduce one version number at csproj file

- Snowflake.Data/Client/SnowflakeDbCommand.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
A couple of handy overloads for constructors of SnowflakeDbConnection and SnowflakeDbCommand. 
Changes: 
- added new (third) constructor for DbCommand that accepts connection and command text
- second constructor of DbCommand now calls default constructor, avoiding code duplication
- added new constructor for DbConnection that accepts connection string
- fixed typo in "Const**r**ucting" word
So instead of 
```cs
using (var connection = new SnowflakeDbConnection())
using (var cmd = new SnowflakeDbCommand(connection))
{
connection.ConnectionString = connectionString;
connection.Open();
cmd.CommandText = query;
// execute reader code...
}
```
you can write it like this: 
```cs
using (var connection = new SnowflakeDbConnection(connectionString))
using (var cmd = new …
```
> Added constructor overload for Command and Connection

- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
Regarding https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/72
Use the session token if it exists instead of the cookie token for the one time token
> Add support for new OKTA OIE to .NET Driver

- Snowflake.Data.Tests/SFStatementTest.cs
- Snowflake.Data/Core/SFStatement.cs
Regarding https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/100
Based off https://github.com/snowflakedb/snowflake-connector-net/pull/573
Checks if there are still characters after a closing comment to prevent index out of bounds error when trimming the SQL query.
Also add test cases for SQL queries with line and block comments
> Fix out of bounds error when trimming SQL

- Snowflake.Data.Tests/HttpUtilTest.cs
- Snowflake.Data/Core/HttpUtil.cs
Regarding https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/72 and https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/117
Connector will retry when receiving HTTP status 429 (Too Many Requests)
> Retry request on HTTP status 429

- Snowflake.Data/Snowflake.Data.csproj
Update Azure.Storage.Blobs from 12.10.0 to 12.13.0 based on https://github.com/snowflakedb/snowflake-connector-net/pull/493
Also update Azure.Storage.Common from 12.9.0 to 12.12.0 due to build error if only Azure.Storage.Blobs was updated - [NU1605: Detected package downgrade: Azure.Storage.Common from 12.12.0 to 12.9.0](https://github.com/snowflakedb/snowflake-connector-net/actions/runs/4106285098/jobs/7084311623#step:7:24)
> Update Azure.Storage dependencies

- Snowflake.Data/Snowflake.Data.csproj
Removed redundant 'NETFRAMEWORK' preprocessor symbol from csproj; this fixes #308 and #536
NETFRAMEWORK is a standard preprocessor symbol that is already defined for builds that target .NET Framework (but not .NET Core builds); therefore defining this symbol in the csproj (with an attempt to exclude it for dotnet-core builds using a regex) is not necessary.
The regex filter was not working as expecting, causing this symbol to be defined for all builds including dotnet core builds.
See here for a list of standard preprocessor symbols: https://learn.microsoft.com/en-us/dotnet/core/tutorials/libraries#how-to-multitarget
> Removed redundant 'NETFRAMEWORK' preprocessor symbol from csproj

- Snowflake.Data.Tests/SFConnectionPoolT.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Core/SFSession.cs
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/257
The root case of this issue is no clean up logic for connection pool. Since the connection pool functions are all static, so no instance for it to handle the application exit. Adding ConnectionPoolSingleton when connection pool being used. The destructor will run when the application exit.
> issue 257 connection not terminate session when connection pooling enable

- .github/workflows/main.yml
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFDbCommandIT.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Core/HeartBeatBackground.cs
- Snowflake.Data/Core/RestResponse.cs
- Snowflake.Data/Core/SFSession.cs
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/307
There were mainly two issues:
1. unhandled exception from heartbeat session renew crashes upper application
2. heartbeat queue growth possibly uncontrolled
The root cause of issue 1 is that when trying to send heart beat for a session, there could be a bad timing that the session token expired so renew session is triggered, and the session is closed right after so renew session could fail, and the unhandled exception was thrown there. 
Removing the exception throw will fix this issue.
There are multiple reason for issue 2 though.
- SFSession.Close() doesn't remove the session out of heart beat queue. https://github.com/snowflakedb/snowflake-connector-net/blob/v2.0.22/Snowflake.Data/Core/SFSession.cs#L258
- …
> SNOW-777930 Bug fix: .NET application terminates when client_session_keep_alive=true due to unhandled exception

- .github/workflows/main.yml
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data/Core/SFSessionProperty.cs
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/308
USER property is mandatory for external browser auth.
root cause is after using DbConnectionStringBuilder, when we have user=;password=; DbConnectionStringBuilder will not add this to connection string properties, but the old version we still add it with empty string. 
solve it by reading the input connection string, if user or password exist, and not exist from DbConnectionStringBuilder, add user or password with empty string.
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/311
Customer can't access lowercase database from connection string. 
root cause is DbConnectionStringBuilder will remove all double quotes in front or after the property value. So for those properties which …
> Bug fix: issue 308, issue 311 

- Snowflake.Data.Tests/Mock/MockRetryUntilRestTimeout.cs
- Snowflake.Data.Tests/SFConnectionPoolT.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Core/RestRequest.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Core/SFStatement.cs
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/362
The root cause was that when OpenAsync() not finish the login process the application close the connection already. In such case the driver pool the invalid connection (session is empty) without any validation, and when it get reused by other connection, the query request failed with 401 error because the session token is empty.
Fix it by adding check of whether the session token is empty before pooling the connection.
Also added logging for session id to get better tracking of the activity for each session in case of using multiple connections in parallel.
> Bug fix for 401 error with empty session token

- Snowflake.Data.Tests/SFConnectionIT.cs
Test SFConnectionIT.TestInvalidProxySettingWithByPassListFromConnectionString() imposes unnecessary restrictions on database host address. This test is passing only if the database host is localhost (or testConfig.account + ".snowflakecomputing.com"). The goal is to make the test pass also for other database hosts.
> SNOW-828109: Remove unnecessary restrictions on database host in tests

- Snowflake.Data.Tests/SecretDetectorTest.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/SFSessionProperty.cs
- Snowflake.Data/Logger/SecretDetector.cs
Bug fix for issue: https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/400
Went through source code and removed all logging of proxy password or entire connection string. 
Added proxypassword to SecretDetector as well to prevent it to be logged in the future, but that would only work in case it's logged with "proxypassword" keyword.
> Do not log proxy credentials

- Snowflake.Data.Tests/SFConnectionPoolT.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Core/SFSession.cs
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/416
The root cause is the improper design of connection pooling feature. It was pooling SnowflakeDBConnection instances and making copy when it's reused from pooling, so it's always possible that the connection hold by different threads could point to the same underlying session.
In the case of issue 416 with `Session no longer exists` error, thread A calls close() to close the connection and the connection get pooled, thread B reuse the connection right after and get the connection out of the pool. Then thread A calls Dispose() on the connection and since it's not pooled, it close the session while it still being used by thread B, and that's why thread B got error of `Session no longer exists`
The error was …
> Bug fix for "Session no longer exists" issue with connection pooling

- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
Revise the fix for issue#52 to fix bugs there
https://github.com/snowflakedb/snowflake-connector-net/pull/610
https://github.com/snowflakedb/snowflake-connector-net/pull/619
https://github.com/snowflakedb/snowflake-connector-net/pull/631
- rollback the retry added for request sending (in requester.cs) since we have retry on request sending in HttpClient.RetryHandler already. Extra retry here is unnecessary
- Reset chunk before retry on chunk downloading in case there could be garbage data left from previous attempt which could fail the chunk parsing
- Fix the bug that backoff time is not set correctly
> Bug fix for retry on chunk downloading

- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Snowflake.Data.csproj
Bug fix for issue#365
The issue was introduced by using WinHttpHandler as a replacement for HttpClientHandler, which was found not a good replacement due to some unexpected behavior changes.
.e.g the root cause of issue#365 likely is the same as issue#404, that WinHttpHandler needs different time out settings.
The purpose of using WinHttpHandler is to fix an issue that when using proxy and set INSECURE_MODE=false, the connection could fail with SSL error.
Per discussion in the issue#365 that actually could be customer proxy setting issue, also using WinHttpHandler doesn't really fix the issue as it's been reported on Linux as well.
The decision here is to remove WinHttpHandler, to remove all unexpected behavior changes with it. For the proxy issue if customer raise it again we can check …
> remove winhttphandler

- .github/workflows/cla_bot.yml
CLA Assistant check has been failing for release branches. The failure is due the jenkins user used to create the branch and do the commit is not in the allow list in that check.
The fix is to add it.
> SNOW-845774 - Add Jenkins user to allow list for cla assistant check

- Snowflake.Data.Tests/HttpUtilTest.cs
- Snowflake.Data/Core/HttpUtil.cs
It is a bug fix that resolves the issue: https://github.com/snowflakedb/snowflake-connector-net/issues/653
The fix is about setting properly UseProxy attribute of HttpClientConfig to indicate whether a proxy is being used.
> SNOW-828572 Set UseProxy on HttpClientHandler

- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
- Snowflake.Data/Snowflake.Data.csproj
Right now github actions build .NET driver for multiple .NET versions out of which 4.7.1 is still supported and enforces c# 7.3.
To spot syntax problems at local env within IDE before submitting a PR we need to default language version to 7.3.
> Default C# version in the IDE to match with github build matrix for supported .net versions

- Snowflake.Data.Tests/App.config
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFConnectionPoolT.cs
- Snowflake.Data.Tests/SFDbTransactionIT.cs
- Snowflake.Data/Client/SnowflakeDbCommand.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Client/SnowflakeDbTransaction.cs
This change introduces an automated rollback during connection close and being pooled.
The rollback will be done on condition that a transaction got started with its constructor or BeginTransaction method of a connection (explicit transaction). If an error on such a rollback occurs the connection won't get added back to the pool to ensure that pool does never provide a dirty (with active transaction) connection.
In case of a transaction started with SnowflakeDbCommand the driver won't keep track of it.
> SNOW-835635 rollback session on connection pooled

- Snowflake.Data.Tests/HttpUtilTest.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFReusableChunkTest.cs
- Snowflake.Data.Tests/SFSessionPropertyTest.cs
- Snowflake.Data.Tests/Session/SFHttpClientPropertiesTest.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
- Snowflake.Data/Core/Session/SFSessionHttpClientProperties.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
sdk issue 457
add new connection parameter `maxHttpRetries` to limit the number of retry attempts.
> add max retry on http request to prevent infinite retry

- Snowflake.Data.Tests/SFBindTestIT.cs
- Snowflake.Data/Core/JsonUtils.cs
When client tried execute command using .net driver then  JSONSerializer can use customer global configuration. If he had set TypeNameHandling=Auto then operation on snowflake was finished with error "SQL compilation error: Unsupported data type 'java.util.LinkedHashMap'".
> Snow 840115 - Set None value for TypeNameHandling in local JsonSerializerSettings

- .github/workflows/cla_bot.yml
Rules do not allow to use `@v2` for CLAAssistant action thus reverting to `@master`.
> SNOW-871776: Revert the version of CLA Assistant to @master

- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Core/Session/SFSession.cs
- Use UTC timestamp for session start time to avoid problems during daylight savings transitions
- Make Session start time private
> SNOW-828591: Use UTC timestamp for session start time

- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
- Add tests to verify that connection is not marked as open (and taken from the pool) when before was unsuccessfully opened because of e.g. invalid user name
> SNOW-828646: Test connection is not reused when not created successfully

- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/SFDbAdaptorIT.cs
- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
Use separate instance for each test case to be sure that tests are properly separated from eachother.
> SNOW-880335: Use separate instance per test case

- .github/workflows/main.yml
Remove the minicover which causes some tests to take very long time (e.g. `TestSimpleLargeResultSet` took almost 40 minutes on Linux and MacOs, whereas it took 5 seconds on Windows) and also update .NET patch to the newest version.
> SNOW-870776: Remove minicover and update dotnet patch version

- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
Update the `Microsoft.NET.Test.Sdk` package to the newest version as it is implicitly dependent on `Newtonsoft.Json`.
This version of Test Sdk uses newest version of the implicit package thus fixes the vulnerability.
> SNOW-874169: Fix Snyk Newtonsoft.Json vulnerability

- Snowflake.Data.Tests/IntegrationTests/SFDbCommandIT.cs
The test is ignored on GCP environment. Check and confirm that it is working on GCP. If not, see if it is possible to fix it.
> SNOW-896750: Check and enable TestSimpleLargeResultSet on GCP

- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
- Snowflake.Data/Snowflake.Data.csproj
Remove unnecessary `net46` mentions in Tests project and add `net472` as target framework.
> SNOW-898541: Cleanup csproj .NET configuration

- Snowflake.Data/Core/FileTransfer/StorageClient/SFSnowflakeAzureClient.cs
SDK issue 624. The endpoint used for PUT/GET on azure was hardcoded and could cause issue with gov cloud accounts which a different endpoint should be used.
Use the endpoint returned from server response in stageInfo to fix the issue.
No test case added as the existing test case can confirm using endpoint from stageInfo works already. Choosing different endpoint for gov cloud accounts is server behavior.
Will ask customer to try with the fix if possible though.
> SNOW-898710 use endpoint from stageInfo for azure

- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data.Tests/UnitTests/SFUriUpdaterTest.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestParams.cs
- Snowflake.Data/Core/Session/SFSessionHttpClientProperties.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
sdk issue156
Add retry reason as http error code in query retry request. 0 when no response received.
Hidden connection parameter `INCLUDERETRYREASON` to allow disable retry reason in retry request, true by default.
> SNOW-736347 [HTAP] add retry reason in query retry request

- Snowflake.Data.Tests/IntegrationTests/SFPutGetTest.cs
- Snowflake.Data/Core/FileTransfer/SFFileMetadata.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFSnowflakeAzureClient.cs
- Fix uploading non compressed file with auto_compress option to Azure
- Fix uploading and downloading non compressed files with auto_compress option with non empty path on the server
> SNOW-888701: Fix uploading with compression

- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/UnitTests/FastParserTest.cs
- Snowflake.Data.Tests/UnitTests/SFDataConverterTest.cs
Setting the culture explicitly allows to run the tests in any locale on a local machine without changing it to `en-US`.
> SNOW-828158: Set Culture explicitly for tests

- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
As mentioned in #762, `IDbConnection` in .NET Standard 2.1 added a new `CloseAsync()` method.
This Pull Request adds functionality targeted at .NET Standard 2.1 (designated by the `NETCOREAPP3_0_OR_GREATER` compiler flag) to add an override for `CloseAsync()`. The compiler flag is required because the codebase also targets .NET Framework 4.7.2, which only supports .NET Standard 2.0 that doesn't have `CloseAsync()`.
This Pull Request negates the need to cast to `SnowflakeDbConnection` to call `CloseAsync(CancellationToken)` in .NET 6 by having `CloseAsync()` call `CloseAsync(CancellationToken.None)`.
This is the code from #538 that was automatically closed when I rebased my fork to resolve merge conflicts.
> SNOW-903956: Add support for CloseAsync() on IDbConnection in .NET 6

- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Core/Session/SessionPool.cs
Extracted session pool to a separate file.
Initial changes to apply naming conventions.
> SNOW-902611 Extract SessionPool to a separate file + naming conventions

- Snowflake.Data.Tests/UnitTests/SFFileTransferAgentTests.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
The PR adds tests for SFFileTransferAgent to increase code coverage
> SNOW-723810: Add coverage for SFFileTransferAgent

- Snowflake.Data.Tests/IntegrationTests/SFDbDataReaderIT.cs
- Snowflake.Data.Tests/UnitTests/SFSessionTest.cs
- Snowflake.Data/Core/ArrowResultSet.cs
- Snowflake.Data/Core/SFResultSet.cs
- Snowflake.Data/Core/SFResultSetMetaData.cs
- Snowflake.Data/Core/Session/SFSession.cs
- Snowflake.Data/Core/Session/SFSessionParameter.cs
sdk issue 693
Some cases for HTAP metadata/parameter removal was missed in September release. Fix them and add test case as well.
> SNOW-933246: adding missed fix for HTAP parameter removal

- Snowflake.Data.Tests/IntegrationTests/SFDbCommandIT.cs
- Snowflake.Data.Tests/IntegrationTests/SFDbDataReaderIT.cs
- Snowflake.Data.Tests/IntegrationTests/SFDbTransactionIT.cs
- Snowflake.Data.Tests/UnitTests/SFDbCommandTest.cs
The PR adds tests for SnowflakeDb classes to increase code coverage
> SNOW-723810: Add coverage for SnowflakeDb classes

- Snowflake.Data/Core/Session/SessionPool.cs
Regarding issue 648
The PR fixes a hanging issue due to a [possible deadlock](https://github.com/snowflakedb/snowflake-connector-net/blob/127343fb4f8a55597df3bf3f20e64e18975fcb62/Snowflake.Data/Core/RestRequester.cs#L54) by using async instead when the finalizer tries to close all the sessions in the pool
> SNOW-914532: Use async for session pool finalizer

- Snowflake.Data/Core/Session/SessionPool.cs
The PR renames the variable to the correct name for ClearAllPoolsAsync
> SNOW-914532: Fix variable name in ClearAllPoolsAsync

- Snowflake.Data.Tests/IntegrationTests/SFPutGetTest.cs
- Snowflake.Data.Tests/UnitTests/SFAzureClientTest.cs
- Snowflake.Data.Tests/UnitTests/SFGCSClientTest.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFSnowflakeAzureClient.cs
SNOW-948463 Removed error information for PUT command for GCP
> SNOW-948463 Removed error information for PUT command for GCP

- Snowflake.Data.Tests/UnitTests/Configuration/EasyLoggingConfigFinderTest.cs
- Snowflake.Data/Configuration/EasyLoggingConfigFinder.cs
Prevent to fail if client config file could not be found because of an unexpected error during the phase of searching in predefined directory. It could happen if for example there is no home folder in the operating system.
> SNOW-856231 easy logging - not fail on directory serch error

- Snowflake.Data/Client/SnowflakeDbConnection.cs
The connection which is not closed properly by the user should not enter the connection pool.
> SNOW-957736: Fix SnowflakeDbConnection.Dispose behaviour

- CodingConventions.md
- Snowflake.Data.Tests/IntegrationTests/SFConnectionPoolIT.cs
- Snowflake.Data.Tests/UnitTests/ConnectionPoolManagerTest.cs
- Snowflake.Data.Tests/UnitTests/SnowflakeDbConnectionPoolTest.cs
- Snowflake.Data.Tests/Util/PoolConfig.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Core/ErrorMessages.resx
- Snowflake.Data/Core/SFError.cs
- Snowflake.Data/Core/Session/ConnectionCacheManager.cs
- Snowflake.Data/Core/Session/ConnectionPoolManager.cs
- Snowflake.Data/Core/Session/ConnectionPoolType.cs
- Snowflake.Data/Core/Session/IConnectionManager.cs
- Snowflake.Data/Core/Session/ISessionFactory.cs
- Snowflake.Data/Core/Session/SFSession.cs
- Snowflake.Data/Core/Session/SessionFactory.cs
- Snowflake.Data/Core/Session/SessionPool.cs
Connection Pool v2
- introduction of connection manager handling multiple pool of sessions
- ability to switch Connection Manager between v1 and v2
- controlling pool settings for each pool independently
- default pool version: v1
> pool/SNOW-902608 #2/4 new pool version v2

- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
Validate account domain to prevent SSRF.
> SNOW-944715 Validate account domain

- README.md
re: SNOW-974746 / #817 
document that we currently do not support bind variables in multi-statement queries, we're getting issues related to this
document-only change, based on https://docs.snowflake.com/en/developer-guide/sql-api/submitting-multiple-statements#specifying-multiple-sql-statements-in-the-request which sems to be valid for all the drivers
> SNOW-974746 document that we currently do not support bind variables in multi-statement queries

- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data.Tests/IntegrationTests/SFConnectionPoolIT.cs
- Snowflake.Data/Core/Session/SFSession.cs
- Snowflake.Data/Core/Session/SessionPool.cs
Avoid closing sessions synchronously with obtained lock
> SNOW-984600 Avoid closing expired sessions synchronously with obtained lock

- .github/workflows/main.yml
Drop obsolete time sync caused by https://github.com/actions/runner/issues/2996
> SNOW-982481 Drop obsolete time sync for macos builds

- Snowflake.Data.Tests/UnitTests/Session/SFHttpClientPropertiesTest.cs
- Snowflake.Data/Core/Session/SFSessionHttpClientProperties.cs
SNOW-961434 Fix usage of insecure mode in connection parameters
> SNOW-961434 Fix usage of insecure mode in connection parameters

- Snowflake.Data.Tests/IntegrationTests/SFDbDataReaderIT.cs
- Snowflake.Data.Tests/UnitTests/ArrowResultChunkTest.cs
- Snowflake.Data/Core/ArrowResultChunk.cs
- Snowflake.Data/Core/ArrowResultSet.cs
- Snowflake.Data/Core/BaseResultChunk.cs
- Snowflake.Data/Core/RestResponse.cs
- Snowflake.Data/Core/SFResultChunk.cs
- Snowflake.Data/Core/SFResultSet.cs
- Snowflake.Data/Snowflake.Data.csproj
Optimizations for arrow processing.
> SNOW-968741: Arrow performance optimizations

- Snowflake.Data.Tests/IntegrationTests/MaxLobSizeIT.cs
Add tests for increased LOB size
> SNOW-969717: Add tests for LOB

- Snowflake.Data/Snowflake.Data.csproj
Replace unmaintained `Portable.BouncyCastle` with `BouncyCastle.Cryptography`.
> SNOW-1009042: Replace Portable.BouncyCastle with BouncyCastle.Cryptography

- Snowflake.Data.Tests/IntegrationTests/EasyLoggingIT.cs
- Snowflake.Data.Tests/Tools/UnixOperationsTest.cs
- Snowflake.Data.Tests/UnitTests/Configuration/EasyLoggingConfigFinderTest.cs
- Snowflake.Data.Tests/UnitTests/Configuration/EasyLoggingConfigGenerator.cs
- Snowflake.Data.Tests/UnitTests/Configuration/EasyLoggingConfigParserTest.cs
- Snowflake.Data.Tests/UnitTests/Tools/UnixOperationsTest.cs
- Snowflake.Data/Configuration/EasyLoggingConfigFinder.cs
- Snowflake.Data/Core/Session/EasyLoggingStarter.cs
- Snowflake.Data/Core/Tools/UnixOperations.cs
- Snowflake.Data/Logger/EasyLoggerManager.cs
> SNOW-990111 Easy Logging more tests and permission check fix

- Snowflake.Data.Tests/UnitTests/SFDbCommandTest.cs
- Snowflake.Data/Client/SnowflakeDbCommand.cs
Add check if command text is set before executing
> SNOW-998036: Add check if command text is set before executing

- README.md
- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data.Tests/IntegrationTests/SFPutGetTest.cs
- Snowflake.Data.Tests/UnitTests/SFFileTransferAgentTests.cs
- Snowflake.Data.Tests/Util/SnowflakeDbExceptionAssert.cs
- Snowflake.Data/Client/SnowflakeDbCommand.cs
- Snowflake.Data/Client/SnowflakeDbException.cs
- Snowflake.Data/Core/ErrorMessages.resx
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
- Snowflake.Data/Core/SFBindUploader.cs
- Snowflake.Data/Core/SFError.cs
- Snowflake.Data/Core/SFStatement.cs
QueryID is super helpful when solving issues but it was not reachable when PUT/GET operation got failed at the command/exception level.
It was not available for successful scenario for PUT/GET commands as well.
This change actually introduces a new type of exception prior to the one used previously - FileNotFoundException/DirectoryNotFoundException and this previous exception is now an inner exception of SnowflakeDbException which we had to use to provide QueryId.
In rare cases (for instance when a connection was not opened) request to PUT/GET file on stage might still end up with a base Exception since QueryId won't be created in such a case.
> SNOW-950923 fix to provide QueryID for failures during GET/PUT file operations

- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
Native OKTA SSO Authn improvements of error handling.
> SNOW-1206259 Handle OKTA Auth invalid responses more gracefully

- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
SNOW-1232318 Fix account name validation to allow account name be even 1 or 2 chars long
> SNOW-1232318 fix account name validation

- Snowflake.Data.Tests/IntegrationTests/SFConnectionPoolIT.cs
- Snowflake.Data.Tests/IntegrationTests/SFDbCommandIT.cs
- Snowflake.Data.Tests/UnitTests/SFStatementTest.cs
- Snowflake.Data/Client/SnowflakeDbCommand.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Core/QueryResultsAwaiter.cs
- Snowflake.Data/Core/RestParams.cs
- Snowflake.Data/Core/RestRequest.cs
- Snowflake.Data/Core/RestResponse.cs
- Snowflake.Data/Core/SFBindUploader.cs
- Snowflake.Data/Core/SFResultSet.cs
- Snowflake.Data/Core/SFStatement.cs
- Snowflake.Data/Core/Session/SFSession.cs
- Adds the option to execute queries in async mode
- Adds the capability to asynchronously wait for the query to finish and get the results using the query ID
- Adds checking the query status
- Adds checking if query is still running or encountered an error
> SNOW-817091: Async execution

- README.md
Async executions documentation.
> SNOW-817091 async executions documentation

- README.md
- Snowflake.Data.Tests/IntegrationTests/ConnectionMultiplePoolsAsyncIT.cs
- Snowflake.Data.Tests/IntegrationTests/ConnectionMultiplePoolsIT.cs
- Snowflake.Data.Tests/IntegrationTests/ConnectionPoolCommonIT.cs
- Snowflake.Data.Tests/IntegrationTests/ConnectionSinglePoolCacheIT.cs
- Snowflake.Data.Tests/IntegrationTests/SFConnectionPoolAsyncIT.cs
- Snowflake.Data.Tests/Mock/MockHelper.cs
- Snowflake.Data.Tests/Mock/TestSnowflakeDbConnection.cs
- Snowflake.Data.Tests/UnitTests/Session/WaitingQueueTest.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Core/Session/ConnectionCacheManager.cs
- Snowflake.Data/Core/Session/ConnectionPoolManager.cs
- Snowflake.Data/Core/Session/IConnectionManager.cs
- Snowflake.Data/Core/Session/SFSession.cs
- Snowflake.Data/Core/Session/SessionPool.cs
Prevent evicted connections from returning to the pool
> Pool/SNOW-937183 Prevent evicted connections from returning to the pool

- .EditorConfig
- .github/workflows/linter.yml
- .github/workflows/main.yml
- .gitignore
Add linter action
- Add linter.yml workflow
- Add .EditorConfig with default rules
- Add .DS_Store to gitignore
> [SNOW-921048]Add linter action

- Snowflake.Data.Tests/UnitTests/SFS3ClientTest.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Add https to endpoints without it
- Add unit test for SetCommonClientConfig
> [SNOW-1313929] Add https to endpoints without it

- README.md
- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
Support for double quote character in delimited identifier.
> SNOW-1053935: Support for double quote character in delimited identifier.

- Snowflake.Data.Tests/UnitTests/ConnectionPoolManagerTest.cs
- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data.Tests/UnitTests/Session/SessionPoolTest.cs
- Snowflake.Data.Tests/UnitTests/Tools/SecureStringHelperTest.cs
- Snowflake.Data/Core/Session/ConnectionPoolManager.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
- Snowflake.Data/Core/Session/SessionPool.cs
- Snowflake.Data/Core/Tools/SecureStringHelper.cs
SNOW-1373257 Make secure password be a part of pool key
> SNOW-1373257 Make secure password be a part of pool key

- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
Disable connection pooling for external browser authentication
> SNOW-1373131 disable connection pooling for external browser authentication

- Snowflake.Data.Tests/UnitTests/ConnectionCacheManagerTest.cs
- Snowflake.Data.Tests/UnitTests/ConnectionPoolManagerTest.cs
- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data.Tests/UnitTests/Session/ConnectionPoolConfigExtractorTest.cs
- Snowflake.Data/Core/Session/SFSessionHttpClientProperties.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
- Snowflake.Data/Core/Session/SessionPool.cs
SNOW-1417631 Disable pooling for jwt token authentication with key file
> Pool/SNOW-1417631 Disable pooling for jwt token authentication wit key file

- Snowflake.Data.Tests/IntegrationTests/ConnectionMultiplePoolsIT.cs
> Fix pool flaky test

- Snowflake.Data.Tests/UnitTests/Session/FixedZeroCounterTest.cs
- Snowflake.Data.Tests/UnitTests/Session/NonNegativeCounterTest.cs
- Snowflake.Data.Tests/UnitTests/Session/NonWaitingQueueTest.cs
- Snowflake.Data.Tests/UnitTests/Session/SessionCreationTokenCounterTest.cs
- Snowflake.Data.Tests/UnitTests/Session/WaitingQueueTest.cs
- Snowflake.Data/Core/Session/ConnectionPoolManager.cs
- Snowflake.Data/Core/Session/ISessionCreationTokenCounter.cs
- Snowflake.Data/Core/Session/IWaitingQueue.cs
- Snowflake.Data/Core/Session/NonCountingSessionCreationTokenCounter.cs
- Snowflake.Data/Core/Session/NonWaitingQueue.cs
- Snowflake.Data/Core/Session/SFSession.cs
- Snowflake.Data/Core/Session/SessionCreationTokenCounter.cs
- Snowflake.Data/Core/Session/SessionPool.cs
- Snowflake.Data/Core/Session/WaitingQueue.cs
SNOW-968914 Break waiting on pool destroy
> SNOW-968914 Break waiting on pool destroy

- doc/Connecting.md
SNOW-1337069 Fix note about special signs in connection string
> SNOW-1337069  connection pool doc fix

- Snowflake.Data/Snowflake.Data.csproj
SNOW-1463590 Bump BouncyCastle.Cryptography dependency to 2.3.1
> SNOW-1463590 Bump BouncyCastle.Cryptography dependency to 2.3.1

- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
- Snowflake.Data/Snowflake.Data.csproj
SNOW-1473274 Sign assembly only when releasing
> SNOW-1473274 Sign assembly only when releasing

- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
SNOW-1526509 Log connecting area
> SNOW-1526509 Log connecting area

- Snowflake.Data.Tests/UnitTests/SFDbCommandTest.cs
- Snowflake.Data/Client/SnowflakeDbCommand.cs
Change Prepare method to be handled as a noop, removed throw NotImplementedException.
> SNOW-973444: Change Prepare to be handled as a Noop

- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Core/HttpUtil.cs
Fix not thrown exception when OpenAsync http request fails
> SNOW-1276398 Fix not thrown exception when OpenAsync http request fails

- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data.Tests/Mock/MockCloseHangingRestRequester.cs
- Snowflake.Data.Tests/UnitTests/SFSessionTest.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Core/Session/SFSession.cs
SNOW-1640968 Make connection finaliser a not blocking operation to avoid blocking garbage collector which could lead to massive memory consumption.
> SNOW-1640968 Make connection finaliser a not blocking operation

- Snowflake.Data/Core/RestRequester.cs
Debugging https://github.com/snowflakedb/snowflake-connector-net/issues/1004 made apparent that it would be more helpful if the errors encountered during communicating with Snowflake would not be 'hidden' under `Debug` loglevel, as enabling `Debug` loglevel for the whole driver causes a lot of logs.
Exposing unsuccessful requests at `Error` loglevel could help see and catch them easier even without needing to enable Debug logs across all the driver.
> SNOW-1612981 loglevel for errors Debug -> Error

- Snowflake.Data/Client/SnowflakeDbDataReader.cs
SNOW-1488701 temporarily disable structured types support
> SNOW-1488701 temporarily disable structured types support

- Snowflake.Data.Tests/IntegrationTests/ConnectionMultiplePoolsAsyncIT.cs
- Snowflake.Data.Tests/IntegrationTests/ConnectionMultiplePoolsIT.cs
- Snowflake.Data.Tests/IntegrationTests/ConnectionPoolChangedSessionIT.cs
- Snowflake.Data.Tests/IntegrationTests/ConnectionPoolCommonIT.cs
- Snowflake.Data.Tests/IntegrationTests/ConnectionSinglePoolCacheAsyncIT.cs
- Snowflake.Data.Tests/IntegrationTests/ConnectionSinglePoolCacheIT.cs
- Snowflake.Data.Tests/UnitTests/ConnectionCacheManagerTest.cs
- Snowflake.Data.Tests/UnitTests/ConnectionPoolManagerTest.cs
- Snowflake.Data.Tests/Util/PoolConfig.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
- Snowflake.Data/Core/Tools/Diagnostics.cs
Fixed connection pool manager allocation problem
Removal of exceptions related to optional connection string parameters
> SNOW-1629635 fix connection pool allocation

- Snowflake.Data.Tests/IntegrationTests/SFDbDataReaderIT.cs
- Snowflake.Data.Tests/IntegrationTests/StructuredTypesWithEmbeddedUnstructuredIT.cs
- Snowflake.Data.Tests/UnitTests/StructuredTypesTest.cs
- Snowflake.Data/Core/ArrowResultChunk.cs
- Snowflake.Data/Core/ArrowResultSet.cs
- Snowflake.Data/Core/Converter/TimeConverter.cs
- Snowflake.Data/Core/SFDataConverter.cs
Set DateTimeKind.Unspecified for TIMESTAMP_NTZ, TIME and DATE including structured types and ARROW/JSON format
> SNOW-1616044 set DateTimeKind.Unspecified for TIMESTAMP_NTZ, TIME and DATE

- Snowflake.Data.Tests/IntegrationTests/SFDbDataReaderGetEnumeratorIT.cs
- Snowflake.Data/Client/SnowflakeDbDataReader.cs
Added implementation of GetEnumerator using DbEnumerator class.
> Added SnowflakeDbDataReader implementation of GetEnumerator using DbEnumerator class

- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data.Tests/Mock/MockS3Client.cs
- Snowflake.Data.Tests/UnitTests/SFS3ClientTest.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Snowflake.Data/Core/HttpUtil.cs
Fix S3 exception casting and flaky tests
We sometimes get `System.InvalidCastException : Unable to cast object of type 'System.Net.Sockets.SocketException' to type 'Amazon.S3.AmazonS3Exception'. `
> SNOW-1739483 Fix S3 exception casting and flaky tests

- Snowflake.Data/Core/HttpUtil.cs
Fix of rounding issue, to avoid the situation with `backOffInSec == 0`:
```
2024-10-24 12:57:16,009 [35] [WARN ] [Snowflake.Data.Log.Log4NetImpllassName:61] - Http request timeout. Retry the request after 1 sec.
2024-10-24 12:57:17,020 [36] [WARN ] [Snowflake.Data.Log.Log4NetImpllassName:61] - Http request timeout. Retry the request after 1 sec.
2024-10-24 12:57:18,036 [36] [WARN ] [Snowflake.Data.Log.Log4NetImpllassName:61] - Http request timeout. Retry the request after 3 sec.
2024-10-24 12:57:21,403 [41] [WARN ] [Snowflake.Data.Log.Log4NetImpllassName:61] - Http request timeout. Retry the request after 0 sec.
2024-10-24 12:57:21,403 [41] [WARN ] [Snowflake.Data.Log.Log4NetImpllassName:61] - Http request timeout. Retry the request after 0 sec.
2024-10-24 12:57:21,403 [41] [WARN ] …
```
> SNOW-1739583 Fix of rounding issue

- Snowflake.Data.Tests/UnitTests/GcmEncryptionProviderTest.cs
- Snowflake.Data.Tests/Util/TestDataGenarator.cs
- Snowflake.Data/Core/FileTransfer/EncryptionProvider.cs
- Snowflake.Data/Core/FileTransfer/GcmEncryptionProvider.cs
- Snowflake.Data/Core/FileTransfer/MaterialDescriptor.cs
- Snowflake.Data/Core/FileTransfer/SFFileMetadata.cs
SNOW-1524245 Gcm encryption using BouncyCastle
> SNOW-1524245 Gcm encryption using BouncyCastle

- Snowflake.Data.Tests/IntegrationTests/SFDbCommandIT.cs
- Snowflake.Data/Core/ResultSetUtil.cs
Fix incorrect row count when executing a COPY INTO command for ExecuteNonQuery and ExecuteNonQueryAsync
> SNOW-1657238: Fix incorrect row count for rows loaded

- Snowflake.Data/Core/HttpUtil.cs
Improve calculation of time to wait before retry
> SNOW-1739483 improve calculation of time to wait before retry

- Snowflake.Data.Tests/IntegrationTests/SFPutGetTest.cs
- Snowflake.Data.Tests/UnitTests/SFAzureClientTest.cs
- Snowflake.Data.Tests/UnitTests/SFGCSClientTest.cs
- Snowflake.Data.Tests/UnitTests/SFRemoteStorageClientTest.cs
- Snowflake.Data.Tests/UnitTests/SFS3ClientTest.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFSnowflakeAzureClient.cs
- Snowflake.Data/Core/RestResponse.cs
If an internal stage is created with SNOWLFAKE_SSE encryption, `encryptionMaterial` isn't returned from Snowflake.
We need to support empty `encryptionMaterial` when client side encryption is disabled and `isClientSideEncrypted` is false.
> SNOW-1672654 Support for empty encryptionMaterial

- README.md
SNOW-1758373 Documentation for package signature verification.
> SNOW-1758373 Documentation for package signature verification

- Snowflake.Data.Tests/UnitTests/GcmEncryptionProviderTest.cs
- Snowflake.Data/Core/FileTransfer/GcmEncryptionProvider.cs
SNOW-1524245 Set initialisation vector length for Gcm encryption to 12 bytes
> SNOW-1524245 Set initialisation vector length for Gcm encryption to 12 bytes

- Snowflake.Data.Tests/UnitTests/SFStatementTest.cs
- Snowflake.Data/Core/SFStatement.cs
SNOW-1805438 Handle null data in failed responses
> SNOW-1805438 Handle null data in failed responses

- Snowflake.Data.Tests/UnitTests/SFAzureClientTest.cs
- Snowflake.Data.Tests/UnitTests/SFGCSClientTest.cs
- Snowflake.Data.Tests/UnitTests/SFS3ClientTest.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFSnowflakeAzureClient.cs
SNOW-1569293 Read encryption headers in a case insensitive way
> SNOW-1569293 Read encryption headers in a case insensitive way

- Snowflake.Data.Tests/UnitTests/SFAzureClientTest.cs
- Snowflake.Data.Tests/UnitTests/SFGCSClientTest.cs
- Snowflake.Data.Tests/UnitTests/SFS3ClientTest.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFSnowflakeAzureClient.cs
SNOW-1887537 Get file without SFC_DIGEST
> SNOW-1887537 Get file without SFC_DIGEST

- Snowflake.Data.Tests/UnitTests/Tools/WiremockRunnerTest.cs
- Snowflake.Data.Tests/Util/WiremockRunner.cs
Rename wiremock port property names and URLs.
> SNOW-1952746: Rename wiremock property names

- Snowflake.Data.Tests/Util/WiremockRunner.cs
SNOW-1952746 Expose wiremock defaults
> SNOW-1952746 Expose wiremock defaults

- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthAuthorizationCodeFlowTest.cs
- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data.Tests/UnitTests/SecretDetectorTest.cs
- Snowflake.Data.Tests/UnitTests/Session/SessionPoolTest.cs
- Snowflake.Data.Tests/UnitTests/SnowflakeDbConnectionTest.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Core/Session/ConnectionPoolManager.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
- Snowflake.Data/Core/Session/SessionPool.cs
- Snowflake.Data/Core/Session/SessionPropertiesContext.cs
- Snowflake.Data/Logger/SecretDetector.cs
SNOW-1917171 use client secret provided externally and recognise hosts
> SNOW-1917171 use client secret provided externally and recognise hosts

- Snowflake.Data.Tests/UnitTests/CredentialManager/SFBaseCredentialManagerTest.cs
- Snowflake.Data/Core/CredentialManager/Infrastructure/SFCredentialManagerWindowsNativeImpl.cs
Fixes reading too many chars from Windows native secret store tokens
> SNOW-1989063: Fix reading tokens in Windows Credential Manager implementation

- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/BaseOAuthFlowTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthAuthorizationCodeFlowTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthCacheKeysTests.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthClientCredentialFlowTest.cs
- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data.Tests/wiremock/OAuth/AuthorizationCode/successful_flow_without_refresh_token.json
- Snowflake.Data.Tests/wiremock/OAuth/ClientCredentials/successful_flow.json
- Snowflake.Data.Tests/wiremock/OAuth/ClientCredentials/successful_without_refresh_token.json
- Snowflake.Data.Tests/wiremock/OAuth/ClientCredentials/token_request_error.json
- Snowflake.Data/Core/Authenticator/OAuthAuthorizationCodeAuthenticator.cs
- Snowflake.Data/Core/Authenticator/OAuthCacheKeys.cs
- Snowflake.Data/Core/Authenticator/OAuthClientCredentialsAuthenticator.cs
- Snowflake.Data/Core/Authenticator/OAuthFlowAuthenticator.cs
- Snowflake.Data/Core/CredentialManager/Infrastructure/SFCredentialManagerInMemoryImpl.cs
- Snowflake.Data/Core/Rest/OAuthAccessTokenRequest.cs
- Snowflake.Data/Core/Rest/OAuthAccessTokenResponse.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
SNOW-1917238 Client Credentials Flow
> SNOW-1917238 Client Credentials Flow

- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data.Tests/UnitTests/Session/SessionPoolTest.cs
- Snowflake.Data/Core/Session/SFSession.cs
- Snowflake.Data/Core/Session/SFSessionHttpClientProperties.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
- Snowflake.Data/Core/Session/SessionPool.cs
Disable pooling by default for oauth authorization code flow.
> Disable pooling by default for oauth authorization code flow

- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthAuthorizationCodeAuthenticatorTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthAuthorizationCodeFlowTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthClientCredentialFlowTest.cs
- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/Authenticator/OAuthFlowAuthenticator.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
- Snowflake.Data/Core/Session/SessionPropertiesContext.cs
Enable http communication to Identity Provider
> Enable http communication to Identity Provider

- Snowflake.Data.Tests/IntegrationTests/SFMultiStatementsIT.cs
- Snowflake.Data/Client/SnowflakeDbCommand.cs
- Snowflake.Data/Client/SnowflakeDbDataReader.cs
- Snowflake.Data/Core/ResultSetUtil.cs
> SNOW-2102617 Enable result sets for DML

- Snowflake.Data.Tests/UnitTests/Session/SessionPoolTest.cs
- Snowflake.Data/Core/QueryContextCache.cs
- Snowflake.Data/Core/Session/SFSession.cs
- Snowflake.Data/Core/Session/SessionPool.cs
SNOW-2139007 Clear query context cache before returning session to pool.
> SNOW-2139007 Clear query context cache before returning session to pool

- Snowflake.Data.Tests/IntegrationTests/SFDbDataReaderIT.cs
- Snowflake.Data.Tests/IntegrationTests/SFMultiStatementsIT.cs
SNOW-2148519 Use json result format in multistatement tests
> SNOW-2148519 Use json result format in multistatement tests

- doc/CertficateValidation.md
This is a doc-only change, no code was changed.
Since we already had at least one customer who got tripped up in their Windows environment wanting to reach out to ctldl.windowsupdate.com, the host being blocked on the network, this leading to unnecessary (up to 20s) connection delays, even if it's entirely out of Snowflake's control , we might want to document and call this out.  
Kudos to @sfc-gh-wfateem for discovering this!
> SNOW-2043017 adding ctldl to readme
