snowflakedb/snowflake-connector-net

- Snowflake.Data/Client/SnowflakeDbCommand.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbTransaction.cs
- Snowflake.Data/Core/IRestRequest.cs
- Snowflake.Data/Core/RestRequestImpl.cs
- Snowflake.Data/Core/SFBaseResultSet.cs
- Snowflake.Data/Core/SFChunkDownloader.cs
- Snowflake.Data/Core/SFResultSet.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Snowflake.Data.csproj
1. How to enable logging? See last section of READMDE.md
2. Does the logging have os version, framework version etc? Yes and No.
Client environment is added to authentication request body, and logged. However, it is really difficult to get framework version at runtime. MS has a ticket for it. https://github.com/dotnet/corefx/issues/17452
3. Sample logging. https://ci.appveyor.com/project/howryu/snowflake-connector-net/build/logging_improve-135/artifacts
> Logging improve

- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Snowflake.Data.csproj
Fix for https://github.com/snowflakedb/snowflake-connector-net/issues/34
> Fix issue in net46 for system.runtime reference

- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data/Core/SFSessionProperty.cs
> Fix the wrong formatting string

- Snowflake.Data/Core/RestResponse.cs
> Change nullresponse.data type from string to object

- Snowflake.Data/Configuration/SFConfiguration.cs
- Snowflake.Data/Core/ChunkDownloaderFactory.cs
This is a temporary fix for #123.
> Add configurable option for chunk downloader

- Snowflake.Data.Tests/SFBindTestIT.cs
- Snowflake.Data/Core/SFDataConverter.cs
In the current code base we just convert the null parameter to empty string.
> Support Null valued Parameter

- Snowflake.Data/Client/SnowflakeDbParameter.cs
This is going to unblock potential case from frameworks such as EntityFrameworkCore
Redo of #145
> @snow-81118 Not being strict on DBParameter

- README.md
- Snowflake.Data.Tests/Mock/MockCloseSessionGone.cs
- Snowflake.Data.Tests/Mock/MockOkta.cs
- Snowflake.Data.Tests/Mock/MockRestSessionExpired.cs
- Snowflake.Data.Tests/Mock/MockRestSessionExpiredInQueryExec.cs
- Snowflake.Data.Tests/Mock/MockServiceName.cs
- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/SFBindTestIT.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFDbAdaptorIT.cs
- Snowflake.Data.Tests/SFDbCommandIT.cs
- Snowflake.Data.Tests/SFDbDataReaderIT.cs
- Snowflake.Data.Tests/SFDbFactoryIT.cs
- Snowflake.Data.Tests/SFDbTransactionIT.cs
- Snowflake.Data/Core/Authenticator/BasicAuthenticator.cs
- Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs
- Snowflake.Data/Core/Authenticator/IAuthenticator.cs
- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
- Snowflake.Data/Core/ErrorMessages.resx
- Snowflake.Data/Core/RestParams.cs
- Snowflake.Data/Core/RestRequest.cs
- Snowflake.Data/Core/RestResponse.cs
- Snowflake.Data/Core/SFError.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Core/SFSessionProperty.cs
Support External browser authentication
> SNOW-68770 .NET External Browser auth support

- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
- Snowflake.Data/Core/SFBlockingChunkDownloader.cs
- Snowflake.Data/Core/SFResultSet.cs
> SNOW-82602 Improve deadlocks in the .NET driver

- Snowflake.Data.Tests/SFDataConverterTest.cs
- Snowflake.Data/Core/SFDataConverter.cs
This is a redo PR for #156 to solve Issue #154
> SNOW-89860 No UTC time conversion for Date type binding

- Snowflake.Data.Tests/SFDbCommandIT.cs
- Snowflake.Data.Tests/SFReusableChunkTest.cs
- Snowflake.Data/Core/ChunkDownloaderFactory.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/ReusableChunkParser.cs
- Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
- Snowflake.Data/Core/SFReusableChunk.cs
> Test PR for PR#161

- Snowflake.Data.Tests/SFUriUpdaterTest.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestParams.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Core/SFStatement.cs
@snow-68056 @snow-80093 implement retryCount, clientStartTime and request_guid parameters
> Start time

- README.md
> SNOW-128172 Delete extra line

- Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
- Snowflake.Data/Logger/Log4netImpl.cs
- Snowflake.Data/Logger/SFLogger.cs
- Snowflake.Data/Logger/SFLoggerEmptyImpl.cs
- Snowflake.Data/Logger/SFLoggerFactory.cs
Documentation for plug-and-play logging design: 
[Plug-&-Play Logging Design.pdf](https://github.com/snowflakedb/snowflake-connector-net/files/5412946/Plug-.-Play.Logging.Design.pdf)
Example of plug-and-play using Serilog:
[PlugAndPlayEx.txt](https://github.com/snowflakedb/snowflake-connector-net/files/5412947/PlugAndPlayEx.txt)
> Plug and play

- README.md
Description
Add examples for key-pair authentication and OAuth to the README file
> SNOW-280651 Add examples for key-pair authentication and OAuth to the README file

- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
- Snowflake.Data/Core/HttpUtil.cs
Changes based on existing PR : https://github.com/snowflakedb/snowflake-connector-net/pull/200
Only added comments detailing the problem.
> Okta Authenticator - Clear sid in cookies to allow login again after first login

- Snowflake.Data/Snowflake.Data.csproj
> SNOW-329903: Bumped up DotNet connector PATCH version from 1.2.0 to 1.2.1

- Snowflake.Data/Client/SnowflakeDbDataReader.cs
- Snowflake.Data/Core/SFBaseResultSet.cs
Skip unnecessary conversion to the default C# type.
> SNOW-344502 - IsDbNull optimization

- README.md
Hi Shige,
I am not sure which reviewer to assign this to. Please feel free to re-assign this if appropriate. Thank you.
--mgilkey
> SNOW-346204: Correct an incorrect INSERT statement.

- Snowflake.Data.Tests/SFDbDataReaderIT.cs
- Snowflake.Data/Client/SnowflakeDbDataReader.cs
- Snowflake.Data/Core/SFDataConverter.cs
The driver was throwing a NotImplementedException for GetBytes and GetChars. This also impacted GetStream which is apparently using GetBytes under the hood.
> SNOW-231960 - Add support for GetBytes, GetChars and GetStream

- Snowflake.Data/Core/Authenticator/IAuthenticator.cs
[issues 313](https://github.com/snowflakedb/snowflake-connector-net/issues/313)
Accept oktapreview.com authenticator URL
https://xxxxxx.oktapreview.com
> SNOW-355530 - Accept oktapreview.com authenticator URL

- Snowflake.Data.Tests/SFDataConverterTest.cs
- Snowflake.Data/Core/SFDataConverter.cs
Credit to @tdg5 for the source code fix.
> SNOW-357759 - Fix critical bug in sf data converter for converting booleans

- README.md
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFDataConverterTest.cs
- Snowflake.Data.Tests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/Authenticator/IAuthenticator.cs
- Snowflake.Data/Core/FastParser.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestRequest.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/SFDataConverter.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Core/SFSessionProperty.cs
- Snowflake.Data/Core/UTF8Buffer.cs
- Snowflake.Data/Snowflake.Data.csproj
Merged last changes from master to prep-1.2.4 for porting the fixes to the 1.2.x branch
> Prep 1.2.4

- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/SFChunkDownloaderV2.cs
This is now even more important because we switched to use http streaming on all platforms.
> Dispose of the Http response to release resources

- Snowflake.Data.Tests/Mock/MockCloseSessionException.cs
- Snowflake.Data.Tests/Mock/MockSnowflakeDbConnection.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Core/SFSession.cs
New feature requested in https://github.com/snowflakedb/snowflake-connector-net/issues/215.
> Add support for CloseAsync

- Snowflake.Data.Tests/Mock/MockCloseSessionException.cs
- Snowflake.Data.Tests/Mock/MockCloseSessionGone.cs
- Snowflake.Data.Tests/Mock/MockOkta.cs
- Snowflake.Data.Tests/Mock/MockRestSessionExpired.cs
- Snowflake.Data.Tests/Mock/MockRestSessionExpiredInQueryExec.cs
- Snowflake.Data.Tests/Mock/MockRetryUntilRestTimeout.cs
- Snowflake.Data.Tests/Mock/MockServiceName.cs
- Snowflake.Data.Tests/Mock/MockSnowflakeDbConnection.cs
- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFDbCommandIT.cs
- Snowflake.Data.Tests/SFSessionPropertyTest.cs
- Snowflake.Data.Tests/SFStatementTest.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbException.cs
- Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs
- Snowflake.Data/Core/Authenticator/KeyPairAuthenticator.cs
- Snowflake.Data/Core/Authenticator/OAuthAuthenticator.cs
- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
- Snowflake.Data/Core/ChunkDownloaderFactory.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/SFBlockingChunkDownloader.cs
- Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
- Snowflake.Data/Core/SFChunkDownloaderV2.cs
- Snowflake.Data/Core/SFResultSet.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Core/SFSessionProperty.cs
- Snowflake.Data/Core/SFStatement.cs
Add proxy support via connection setting.
> SNOW-361754 - Add proxy support

- Snowflake.Data.Tests/SFDataConverterTest.cs
- Snowflake.Data.Tests/SFDbDataReaderIT.cs
- Snowflake.Data/Client/SnowflakeDbDataReader.cs
- Snowflake.Data/Core/SFDataConverter.cs
Add getTimeSpan to SnowflakeDbDataReader for retrieving TIME data as Timespan
> Add getTimeSpan to SnowflakeDbDataReader

- README.md
Description
Document support for proxies and two new methods (SnowflakeDbDataReader.getTimeSpan and SnowflakeDbConnection.CloseAsync).
> SNOW-399633 Document support for proxies and two new methods

- Snowflake.Data/Core/RestRequester.cs
Remove the 'Post response' log and duplicate logging
> Http log revision

- Snowflake.Data.Tests/SFDbDataReaderIT.cs
- Snowflake.Data/Core/ResultSetUtil.cs
- Snowflake.Data/Core/SFBaseResultSet.cs
- Snowflake.Data/Core/SFResultSet.cs
Copy into advance the cursor to get the row update information but does not rewind the cursor breaking result set retrieval afterwards.
> SNOW-172987 - COPY INTO error

- .github/workflows/main.yml
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFDbAdaptorIT.cs
- Snowflake.Data.Tests/SFDbCommandIT.cs
- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
- Snowflake.Data/Snowflake.Data.csproj
> GitHub actions non windows

- Snowflake.Data/Core/SFDataConverter.cs
> Return TIMESTAMP as DateTimeKind.Unspecified

- Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs
> Fix external browser auth for non-Windows

- Snowflake.Data.Tests/SFReusableChunkTest.cs
- Snowflake.Data/Client/SnowflakeDbDataReader.cs
- Snowflake.Data/Core/ChunkDeserializer.cs
- Snowflake.Data/Core/ChunkStreamingParser.cs
- Snowflake.Data/Core/IChunkParser.cs
- Snowflake.Data/Core/ReusableChunkParser.cs
- Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
> Async chunk downloader

- Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs
- Snowflake.Data/Core/SFDataConverter.cs
- Snowflake.Data/Snowflake.Data.csproj
SNOW-530859: Bumped up DotNet connector PATCH version from 1.2.8 to 1.2.9
> SNOW-530859: Bumped up DotNet connector PATCH version from 1.2.8 to 1.2.9

- README.md
Minor update for .NET version support.
> Mheavin snow 441998 net connector oath

- README.md
Removed GET and PUT limitations
Testing
> SNOW--494160-dotnet-get

- Snowflake.Data.Tests/SFPutGetTest.cs
- Snowflake.Data/Core/FileTransfer/EncryptionProvider.cs
- Snowflake.Data/Core/FileTransfer/SFFileMetadata.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/ISFRemoteStorageClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFLocalStorageUtil.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFRemoteStorageUtil.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFSnowflakeAzureClient.cs
- Snowflake.Data/Core/RestResponse.cs
Compression option tests are currently not included in this PR
> Implement GET Command

- Snowflake.Data/Core/Authenticator/KeyPairAuthenticator.cs
> Add more details to error when private key string is incorrect

- Snowflake.Data/Core/FileTransfer/EncryptionProvider.cs
Based on https://github.com/snowflakedb/snowflake-connector-net/pull/438#discussion_r860035111
> Read and write bytes in chunks for CreateEncryptedBytes

- Snowflake.Data.Tests/SFDelCharT.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
- Snowflake.Data/Core/ReusableChunkParser.cs
- Snowflake.Data/Core/SFReusableChunk.cs
bug fix at ReusableChunkParser.cs and I created a test case for this.
> snow-502 00374258 DEL character issue

- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Core/SFSessionProperty.cs
use "disableretry=true" on connection string to disable retry
> snow-561 add option to disable retry

- Snowflake.Data.Tests/Mock/MockSnowflakeDbConnection.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data/Client/SnowflakeDbCommand.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbDataReader.cs
- Snowflake.Data/Client/SnowflakeDbException.cs
- Snowflake.Data/Core/Authenticator/KeyPairAuthenticator.cs
- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
- Snowflake.Data/Core/RestRequester.cs
- Snowflake.Data/Core/SFSession.cs
Based off https://github.com/snowflakedb/snowflake-connector-net/pull/452/
> Correct the exception usage

- Snowflake.Data/Snowflake.Data.csproj
Update package version from testing identified. Set to new version for next release.
> SNOW-616992: Bumped up DotNet connector PATCH version to 2.0.14

- Snowflake.Data.Tests/SFStatementTest.cs
- Snowflake.Data.Tests/SFStatementTypeTest.cs
> Add test case for CALL statement type

- README.md
Added the Bind Array Variables section.
> SNOW-572396 dotnet bind array docs update

- Snowflake.Data.Tests/SFReusableChunkTest.cs
- Snowflake.Data/Core/ReusableChunkParser.cs
> Fix DEL char being added an extra 'u' character

- .github/workflows/main.yml
- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
- Snowflake.Data/Snowflake.Data.csproj
> Target .NET 6.0

- Snowflake.Data.Tests/SFConnectionPoolT.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
You can't edit a list inside a foreach loop
We can use toList to copy the list to avoid this issue
closes #497
> You cannot edit a list while the list is being enumerated.

- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFSnowflakeAzureClient.cs
Check error code to determine HTTP errors from PUT/GET requests
> Refactor error handling for remote storage clients

- Snowflake.Data.Tests/SFBindTestIT.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFConnectionPoolT.cs
- Snowflake.Data.Tests/SFDbCommandIT.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/ISFRemoteStorageClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFRemoteStorageUtil.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFSnowflakeAzureClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFStorageClientUtil.cs
- Snowflake.Data/Core/SFBindUploader.cs
- Snowflake.Data/Core/SFSession.cs
- Snowflake.Data/Core/SFStatement.cs
support async, ExecuteNonQueryAsync, ExecuteScalarAsync, ExecuteDbDataReaderAsync ...
> adding async api

- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
salesforce 00399934, fix authentication token is expired issue.
> remove all expired sessions on getConnection

- Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs
- Snowflake.Data/Core/SFError.cs
add check to prevent command injection vulnerability
> check command injection vulnerability

- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Snowflake.Data.csproj
Based off SF# 00396351
Allows connecting through proxy with insecuremode=false
> Use WinHttpHandler for requests on Windows

- README.md
Would you please review the updates for technical accuracy.
> SNOW-682118 Add samples for special characters

- Snowflake.Data.Tests/SFPutGetTest.cs
- Snowflake.Data/Core/FileTransfer/SFFileCompressionTypes.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
- Snowflake.Data/Core/SFResultSet.cs
- Snowflake.Data/Core/SFStatement.cs
Run tests for PR https://github.com/snowflakedb/snowflake-connector-net/pull/547
> PR 547 Tests

- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data/Core/SFSession.cs
CLIENT_SESSION_KEEP_ALIVE=true causes 401 response #557 
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/74
> fix keep alive error issue

- README.md
Add information to the README to run OpenCover and get the code coverage results manually
> Update README with steps to retrieve code coverage manually

- Snowflake.Data/Client/SnowflakeDbCommand.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
Changed exception throwing to better follow best practices to preserve stack trace.
> Exception best practices

- Snowflake.Data.Tests/SFDbCommandIT.cs
- Snowflake.Data.Tests/SFPutGetTest.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
- Snowflake.Data/Core/SFSessionProperty.cs
Regarding issue 92
Support using GCS access token for PUT/GET queries
> Use GCS access token for upload/download

- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
handle the url contains '[' and ']'
> handle the special case for the fips for issue 75

- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
Regarding issue 72
Reverting PR https://github.com/snowflakedb/snowflake-connector-net/pull/578 until Okta OIE changes are released on server side
> Revert "Add support for new OKTA OIE to .NET Driver"

- Snowflake.Data/Core/Authenticator/OktaAuthenticator.cs
Regarding issue 72
Re-adding PR https://github.com/snowflakedb/snowflake-connector-net/pull/578. Testing confirmed for .NET
> Undo revert OKTA OIE

- README.md
Updated the private key example, per Dicky.
> DOC-582 Remove Replace from private key

- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/75
adding "https" when the given url missing it for fips
> adding https when the endpoint missing https

- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data/Core/HttpUtil.cs
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/52
> for issue 52, increase retry to 6 times to avoid incomplete json response

- Snowflake.Data.Tests/SFMultiStatementsIT.cs
- Snowflake.Data/Core/HttpUtil.cs
- Snowflake.Data/Core/RestRequest.cs
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/295
The original PR is https://github.com/snowflakedb/snowflake-connector-net/pull/561
This PR copies all changes from the original PR to run test. Please see the original PR for change details.
> SNOW-770151 Use win http handler for net framework only (from original PR #561)

- README.md
Add batch SQL statement execution
> DOC-661 Add batch execution feature

- .github/workflows/main.yml
- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
- Snowflake.Data/Snowflake.Data.csproj
https://github.com/snowflakedb/snowflake-sdks-drivers-issues-teamwork/issues/140
removed 4.7.2, since we support from 4.7.1 now. but keep the test on both 4.7.1 and 4.7.2
> Fix issue 140, .net support net framework 4.7.1

- README.md
Removed Windows only limitation
> DOC-757 Remove Windows limitation

- Snowflake.Data/Snowflake.Data.csproj
> SNOW-824375_dotnet_connector_version_bump

- .github/workflows/cla_bot.yml
> SNOW-829489: Fix CLA Bot

- Snowflake.Data/Snowflake.Data.csproj
> SNOW-837512_dotnet_connector_version_bump

- Snowflake.Data.Tests/SFDbCommandIT.cs
- Snowflake.Data.Tests/SFReusableChunkTest.cs
- Snowflake.Data/Configuration/SFConfiguration.cs
- Snowflake.Data/Core/ChunkDownloaderFactory.cs
- Snowflake.Data/Core/ChunkParserFactory.cs
- Snowflake.Data/Core/IChunkParserFactory.cs
- Snowflake.Data/Core/SFBlockingChunkDownloader.cs
- Snowflake.Data/Core/SFBlockingChunkDownloaderV3.cs
- Snowflake.Data/Core/SFChunkDownloaderV2.cs
- Snowflake.Data/Core/SFReusableChunk.cs
- Fixed reset of chunk download process when exceptions are thrown during the download
- Removed FORCEPARSEERROR from production code (introduced for testing) 
- Improved testing of chunk downloading process
- Enabled tests for V1 Result Parser and v2 Chunk Downloader
> SNOW-831638 Fixed problem in chunk retry downloading process and improved testing of those retries

- Snowflake.Data.Tests/ChunkDeserializerTest.cs
- Snowflake.Data.Tests/ChunkParserFactoryTest.cs
The PR adds tests for ChunkParserFactory and ChunkDeserializer to increase code coverage
> Add tests for ChunkParserFactory and ChunkDeserializer

- Snowflake.Data.Tests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs
- Snowflake.Data/Core/ErrorMessages.resx
- Snowflake.Data/Core/SFError.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
Added timeout for authentication in external browser. 
Default timeout is set to 120s by parameter BROWSER_RESPONSE_TIMEOUT.
> SNOW-828695 Timeout for authentication in external browser

- Snowflake.Data.Tests/ChunkDownloaderFactoryTest.cs
- Snowflake.Data.Tests/ChunkStreamingParserTest.cs
- Snowflake.Data/Core/SFResultChunk.cs
The PR adds tests for ChunkStreamingParser and ChunkDownloaderFactory to increase code coverage
> Add tests for ChunkStreamingParser and ChunkDownloaderFactory

- Snowflake.Data.Tests/ConcatenatedStreamTest.cs
- Snowflake.Data.Tests/FastMemoryStreamTest.cs
- Snowflake.Data/Core/FastMemoryStream.cs
The PR adds tests for ConcatenatedStream and FastMemoryStream to increase code coverage
> Add tests for ConcatenatedStream and FastMemoryStream

- Snowflake.Data.Tests/SFPutGetTest.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFRemoteStorageUtil.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFSnowflakeAzureClient.cs
Proper handling of remote path containing a sub-directory in GET command
> SNOW-850048 Hanlde of subdirectiores by GET from stage

- .pre-commit-config.yaml
> SNOW-869763 Upgrade secret-scanner to version 1.20

- .github/workflows/main.yml
- .github/workflows/snyk-pr.yml
- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/SFConnectionIT.cs
Prepare the test code to be able to run in parallel and enable the parallelisation within GitHub actions.
> SNOW-861926 Build and test parallelisation and cleanup

- .github/workflows/cla_bot.yml
Add snyk user `sfc-gh-snyk-sca-sa` to CLAAssistant allowlist.
> SNOW-870818: Add Snyk to CLAAssistant allowlist

- .github/workflows/cla_bot.yml
- .github/workflows/jira_close.yml
- .github/workflows/jira_comment.yml
- .github/workflows/jira_issue.yml
- .github/workflows/main.yml
- .github/workflows/snyk-pr.yml
Update the github actions versions to the newest ones available and keep the version consistency between the different actions
> SNOW-871778: Update GitHub actions

- Snowflake.Data/Snowflake.Data.csproj
> SNOW-875424: Bumped up DotNet connector MINOR version from 2.0.26 to 2.1.0

- Snowflake.Data.Tests/App.config
- Snowflake.Data.Tests/SFPutGetTest.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
Fix the usage of `*` and `?` in the file path and refactor the wildcard processing code.
> SNOW-844304: Fix wildcard usage in path

- Snowflake.Data.Tests/SFDbAdaptorIT.cs
- Snowflake.Data.Tests/SFLoggerTest.cs
- Snowflake.Data/Logger/SFLoggerFactory.cs
The PR adds tests for SFLogger and SnowflakeDbDataAdapter to increase code coverage
> Add tests for SFLogger and SnowflakeDbDataAdapter

- .github/workflows/main.yml
- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/SFPutGetTest.cs
- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
Prepare tests performance artifact after test run to be able to compare the difference between environments if needed.
> SNOW-879621: Create tests performance artifact

- .github/workflows/main.yml
- Snowflake.Data.Tests/SFBaseTest.cs
Fix the artifact path as for linux and mac these artifacts are not yet picked up.
> SNOW-879621: Fix artifact path

- .github/workflows/main.yml
- Do not cancel other matrix builds when one fails
- Cancel build when new code in branch appears
> SNOW-880397: Do not cancel other matrix builds when one fails

- Snowflake.Data.Tests/SFDbParameterCollectionTest.cs
- Snowflake.Data.Tests/SFDbParameterTest.cs
The PR adds tests for SnowflakeDbParameter and SnowflakeDbParameterCollection to increase code coverage
> Add tests for SnowflakeDbParameter and SnowflakeDbParameterCollection

- .github/PULL_REQUEST_TEMPLATE.md
> SNOW-887877: Introduce PR Template

- Snowflake.Data.Tests/UnitTests/SFDbParameterCollectionTest.cs
- Snowflake.Data.Tests/UnitTests/SFDbParameterTest.cs
Move unit tests to unit tests folder.
> SNOW-886594: Move tests to specific folder

- Snowflake.Data.Tests/IntegrationTests/SFPutGetTest.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Snowflake.Data/Core/HttpUtil.cs
Fixed hanging of PUT/GET on AWS
> SNOW-862123 Fixed hanging of PUT/GET on AWS

- Snowflake.Data/Snowflake.Data.csproj
> SNOW-897248: Bumped up DotNet connector PATCH version from 2.1.0 to 2.1.1

- .github/workflows/main.yml
- Snowflake.Data/Snowflake.Data.csproj
Use `dotnet-coverage` for the coverage of the code.
> SNOW-897575: Microsoft Code Coverage tool

- Snowflake.Data.Tests/Mock/MockGCSClient.cs
- Snowflake.Data.Tests/UnitTests/SFGCSClientTest.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
The PR adds tests for SFGCSClient to increase code coverage
> SNOW-723810: Add code coverage for GCS client

- .gitignore
As a result of running the tests a file with performance information is created. These files should not be included in any commit so I add them to .gitignore.
> Git ignore test performance reports

- Snowflake.Data/Snowflake.Data.csproj
> SNOW-921831: Bumped up DotNet connector PATCH version from 2.1.1 to 2.1.2

- .github/workflows/jira_comment.yml
Excluded codecov bot from Jira comment Github action
> SNOW-859636 Excluded codecod[bot] from Jira comment action

- Snowflake.Data/Snowflake.Data.csproj
PATCH: Bumped up DotNet connector PATCH version from 2.1.4 to 2.1.5
> PATCH: Bumped up DotNet connector PATCH version from 2.1.4 to 2.1.5

- Snowflake.Data/Core/Snowflake.cs
- Snowflake.Data/Snowflake.Data.csproj
These changes are necessary for the `Release` build with strong name to pass.
> SNOW-829779: Strong Name assembly preparation

- Snowflake.Data/Snowflake.Data.csproj
Bumped up DotNet connector MINOR version from 2.1.5 to 2.2.0
> MINOR: Bumped up DotNet connector MINOR version from 2.1.5 to 2.2.0

- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
Timeout delta increased to verify Login Request Timeout falls into expected range.
> SNOW-950923 Flaky test fix

- README.md
SNOW-990111 Update easy logging documentation
> SNOW-990111 Update easy logging documentation

- Snowflake.Data/Snowflake.Data.csproj
MINOR: Bumped up DotNet connector MINOR version from 3.0.0 to 3.1.0
> MINOR: Bumped up DotNet connector MINOR version from 3.0.0 to 3.1.0

- .github/PULL_REQUEST_TEMPLATE.md
Fix coding conventions PR template
> Fix coding conventions PR template

- SECURITY.md
> SNOW-1293828 Updated security policy

- Snowflake.Data.Tests/UnitTests/Session/WaitingQueueTest.cs
Fix flaky test TestWaitUntilResourceAvailable
> Fix flaky test TestWaitUntilResourceAvailable

- .github/workflows/main.yml
- Snowflake.Data.Tests/IntegrationTests/ConnectionMultiplePoolsAsyncIT.cs
- Snowflake.Data.Tests/UnitTests/Session/SessionPoolTest.cs
- Snowflake.Data/Core/Session/ConnectionPoolManager.cs
- Snowflake.Data/Core/Session/IWaitingQueue.cs
- Snowflake.Data/Core/Session/NonWaitingQueue.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
- Snowflake.Data/Core/Session/SessionPool.cs
- Snowflake.Data/Core/Session/SessionPoolState.cs
- Snowflake.Data/Core/Session/WaitingQueue.cs
- Snowflake.Data/Snowflake.Data.csproj
> SNOW-986233 Log pool status

- Snowflake.Data.Tests/Mock/MockLoginStoringRestRequester.cs
- Snowflake.Data.Tests/UnitTests/SFSessionTest.cs
SNOW-1406763 Test for password with special characters
> SNOW-1406763 Test for password with special characters

- doc/Connecting.md
> Improve documentation

- Snowflake.Data/Core/Session/SFSession.cs
SNOW-968914 Log closing sessions
> SNOW-968914 Log closing sessions

- .pre-commit-config.yaml
- Snowflake.Data.Tests/UnitTests/SecretDetectorTest.cs
- Snowflake.Data/Logger/SecretDetector.cs
SNOW-1452613 Update secret detector
> SNOW-1452613 Update secret detector

- deploy.bat
.NET driver signing assembly with strong name
> Snow 991583 strong assembly sign

- doc/QueryingData.md
third attempt to get this into the docs ;) 
co-authored by @sfc-gh-hachouraria
> example for binding an array as a variable

- Snowflake.Data/Snowflake.Data.csproj
MAJOR: Bumped up DotNet connector MAJOR version from 3.1.0 to 4.0.0
> MAJOR: Bumped up DotNet connector MAJOR version from 3.1.0 to 4.0.0

- Snowflake.Data/Snowflake.Data.csproj
> MINOR: Bumped up DotNet connector MINOR version from 4.0.0 to 4.1.0

- Snowflake.Data.Tests/IntegrationTests/SFBindTestIT.cs
- Snowflake.Data.Tests/Mock/MockGCSClient.cs
- Snowflake.Data.Tests/UnitTests/SFGCSClientTest.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
- Snowflake.Data/Core/SFStatement.cs
> SNOW-1736920 Fix bindings uploading and error handling for GCP

- README.md
> SNOW-1756807: Add note about GCP regional endpoints

- Snowflake.Data/Snowflake.Data.csproj
MINOR: Bumped up DotNet connector MINOR version from 4.1.0 to 4.2.0
> MINOR: Bumped up DotNet connector MINOR version from 4.1.0 to 4.2.0

- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
> SNOW-1889398: Handle endpoint without protocol for GCS

- Snowflake.Data/Core/Authenticator/ExternalBrowserAuthenticator.cs
- Snowflake.Data/Core/Authenticator/KeyPairAuthenticator.cs
SNOW-715504 Fix secondary authentication data in authenticators
> SNOW-715504 Fix secondary authentication data in authenticators

- Snowflake.Data/Core/CredentialManager/Infrastructure/SFCredentialManagerWindowsNativeImpl.cs
SNOW-715504 Add attribution note
> SNOW-715504 Add attribution note

- Snowflake.Data.Tests/IntegrationTests/MaxLobSizeIT.cs
- Snowflake.Data.Tests/IntegrationTests/SFPutGetTest.cs
- Snowflake.Data.Tests/Mock/MockUnixOperations.cs
- Snowflake.Data.Tests/UnitTests/CredentialManager/SFCredentialManagerFileImplTest.cs
- Snowflake.Data.Tests/UnitTests/Logger/EasyLoggingStarterTest.cs
- Snowflake.Data.Tests/UnitTests/SFAzureClientTest.cs
- Snowflake.Data.Tests/UnitTests/SFBindUploaderTest.cs
- Snowflake.Data.Tests/UnitTests/Tools/DirectoryOperationsTest.cs
- Snowflake.Data.Tests/UnitTests/Tools/FileOperationsTest.cs
- Snowflake.Data.Tests/UnitTests/Tools/UnixOperationsTest.cs
- Snowflake.Data/Core/CredentialManager/Infrastructure/SFCredentialManagerFileImpl.cs
- Snowflake.Data/Core/FileTransfer/EncryptionProvider.cs
- Snowflake.Data/Core/FileTransfer/SFFileTransferAgent.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFGCSClient.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFLocalStorageUtil.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFRemoteStorageUtil.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFS3Client.cs
- Snowflake.Data/Core/FileTransfer/StorageClient/SFSnowflakeAzureClient.cs
- Snowflake.Data/Core/Session/EasyLoggingStarter.cs
- Snowflake.Data/Core/Tools/DirectoryOperations.cs
- Snowflake.Data/Core/Tools/FileOperations.cs
- Snowflake.Data/Core/Tools/TempUtil.cs
- Snowflake.Data/Core/Tools/UnixOperations.cs
> SNOW-1706569: Fix file permissions

- Snowflake.Data/Snowflake.Data.csproj
MINOR: Bumped up DotNet connector MINOR version from 4.2.0 to 4.3.0
> MINOR: Bumped up DotNet connector MINOR version from 4.2.0 to 4.3.0

- .gitignore
SNOW-1881731 Add p8 files to .gitignore
> SNOW-1881731 Add p8 files to .gitignore

- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthAuthorizationCodeAuthenticatorTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthAuthorizationCodeFlowTest.cs
- Snowflake.Data/Core/Authenticator/Browser/WebListenerStarter.cs
- Snowflake.Data/Core/Authenticator/OAuthAuthorizationCodeAuthenticator.cs
- Snowflake.Data/Core/RestParams.cs
SNOW-1917171 add default redirect uri
> SNOW-1917171 add default redirect uri

- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthAuthorizationCodeFlowTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthCacheKeysTests.cs
- Snowflake.Data.Tests/Util/StringTransformation.cs
- Snowflake.Data.Tests/Util/WiremockRunner.cs
- Snowflake.Data.Tests/wiremock/OAuth/AuthorizationCode/refresh_token.json
- Snowflake.Data.Tests/wiremock/OAuth/AuthorizationCode/successful_flow.json
- Snowflake.Data.Tests/wiremock/OAuth/snowflake_invalid_token_login.json
- Snowflake.Data/Core/Authenticator/OAuthAuthorizationCodeAuthenticator.cs
- Snowflake.Data/Core/Authenticator/OAuthCacheKeys.cs
- Snowflake.Data/Core/CredentialManager/TokenType.cs
- Snowflake.Data/Core/Rest/BaseOAuthAccessTokenRequest.cs
- Snowflake.Data/Core/Rest/OAuthAccessTokenRequest.cs
- Snowflake.Data/Core/Rest/OAuthRefreshAccessTokenRequest.cs
- Snowflake.Data/Core/SFError.cs
- Snowflake.Data/Core/Session/SFSession.cs
SNOW-1917171 use cache and refresh token
> SNOW-1917171 use cache and refresh token

- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthAuthorizationCodeFlowTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthCacheKeysTests.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthClientCredentialFlowTest.cs
- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data.Tests/UnitTests/Session/SFHttpClientPropertiesTest.cs
- Snowflake.Data/Core/Authenticator/OAuthCacheKeys.cs
- Snowflake.Data/Core/Authenticator/OAuthFlowAuthenticator.cs
- Snowflake.Data/Core/Session/SFSessionHttpClientProperties.cs
- Snowflake.Data/Core/Session/SFSessionParameter.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
Client store temporary credential flag
> Client store temporary credential flag

- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthAuthorizationCodeAuthenticatorTest.cs
- Snowflake.Data/Core/Authenticator/OAuthAuthorizationCodeAuthenticator.cs
Fix redirect uri default url in authorization code flow
> Fix redirect uri default url in authorization code flow

- Snowflake.Data.Tests/AuthenticationTests/AuthConnectionString.cs
- Snowflake.Data.Tests/AuthenticationTests/AuthTestHelper.cs
- Snowflake.Data.Tests/AuthenticationTests/OauthConnectionTest.cs
- Snowflake.Data.Tests/AuthenticationTests/OktaAuthorizationCodeTest.cs
- Snowflake.Data.Tests/AuthenticationTests/OktaClientsCredentialsTest.cs
- Snowflake.Data.Tests/AuthenticationTests/SnowflakeAuthorizationCodeTest.cs
- Snowflake.Data.Tests/AuthenticationTests/SnowflakeAuthorizationCodeWilidcardsTest.cs
- ci/test_authentication.sh
SNOW-1927346: Add OAuth flow tests
> SNOW-1927346: Add OAuth flow tests

- Snowflake.Data/Core/Authenticator/OAuthFlowAuthenticator.cs
- Snowflake.Data/Core/Rest/BaseOAuthAccessTokenRequest.cs
- Snowflake.Data/Core/Rest/RestRequestWrapper.cs
Shorten rest timeout for oauth flows.
> Shorten rest timeout for oauth flows

- Snowflake.Data/Snowflake.Data.csproj
MINOR: Bumped up DotNet connector MINOR version from 4.3.0 to 4.4.0
> MINOR: Bumped up DotNet connector MINOR version from 4.3.0 to 4.4.0

- Snowflake.Data.Tests/UnitTests/SFSessionPropertyTest.cs
- Snowflake.Data/Core/Session/SFSessionProperty.cs
Add check for a protocol in external oauth flow urls
> Add check for a protocol in external oauth flow urls

- Snowflake.Data.Tests/AuthenticationTests/AuthTestHelper.cs
- Snowflake.Data.Tests/AuthenticationTests/OktaAuthorizationCodeTest.cs
- Snowflake.Data.Tests/AuthenticationTests/SnowflakeAuthorizationCodeTest.cs
- Snowflake.Data.Tests/AuthenticationTests/SnowflakeAuthorizationCodeWilidcardsTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/OAuthAuthorizationCodeAuthenticatorTest.cs
- Snowflake.Data/Core/Authenticator/Browser/WebBrowserListener.cs
- Snowflake.Data/Core/Authenticator/OAuthAuthorizationCodeAuthenticator.cs
- Snowflake.Data/Core/Authenticator/OAuthFlowAuthenticator.cs
- Snowflake.Data/Core/Rest/OAuthAccessTokenResponse.cs
> More logs, refactor

- Snowflake.Data.Tests/IntegrationTests/ConnectionMultiplePoolsIT.cs
- Snowflake.Data.Tests/IntegrationTests/ConnectionPoolCommonIT.cs
- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data.Tests/Mock/MockSnowflakeDbConnection.cs
- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Core/SFStatement.cs
- Snowflake.Data/Core/Session/SessionPoolState.cs
Fix for returning cancelled sessions to the connection pool
> SNOW-2044393 Fix for returning cancelled sessions to the connection pool

- Snowflake.Data.Tests/Mock/MockUnixOperations.cs
- Snowflake.Data.Tests/UnitTests/Configuration/EasyLoggingConfigFinderTest.cs
- Snowflake.Data.Tests/UnitTests/Configuration/EasyLoggingConfigParserTest.cs
- Snowflake.Data.Tests/UnitTests/Tools/FileOperationsTest.cs
- Snowflake.Data.Tests/UnitTests/Tools/UnixOperationsTest.cs
- Snowflake.Data/Configuration/EasyLoggingConfigFinder.cs
- Snowflake.Data/Configuration/EasyLoggingConfigParser.cs
- Snowflake.Data/Core/Tools/FileOperations.cs
- Snowflake.Data/Core/Tools/UnixOperations.cs
SNOW-1156046: Fix race condition with easy logging config
> SNOW-1156046: Fix race condition with easy logging config

- Snowflake.Data/Snowflake.Data.csproj
PATCH: Bumped up DotNet connector PATCH version from 4.4.0 to 4.4.1
> PATCH: Bumped up DotNet connector PATCH version from 4.4.0 to 4.4.1

- README.md
Fix advisories link in Readme file
> Fix advisories link in Readme file

- README.md
- Snowflake.Data.Tests/IntegrationTests/ConnectionMultiplePoolsIT.cs
- Snowflake.Data.Tests/IntegrationTests/ConnectionPoolCommonIT.cs
- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data.Tests/Mock/MockSnowflakeDbConnection.cs
- Snowflake.Data.Tests/Mock/MockUnixOperations.cs
- Snowflake.Data.Tests/UnitTests/Configuration/EasyLoggingConfigFinderTest.cs
- Snowflake.Data.Tests/UnitTests/Configuration/EasyLoggingConfigParserTest.cs
- Snowflake.Data.Tests/UnitTests/Tools/FileOperationsTest.cs
- Snowflake.Data.Tests/UnitTests/Tools/UnixOperationsTest.cs
- Snowflake.Data/Client/SnowflakeDbConnection.cs
- Snowflake.Data/Client/SnowflakeDbConnectionPool.cs
- Snowflake.Data/Configuration/EasyLoggingConfigFinder.cs
- Snowflake.Data/Configuration/EasyLoggingConfigParser.cs
- Snowflake.Data/Core/SFStatement.cs
- Snowflake.Data/Core/Session/SessionPoolState.cs
- Snowflake.Data/Core/Tools/FileOperations.cs
- Snowflake.Data/Core/Tools/UnixOperations.cs
- Snowflake.Data/Snowflake.Data.csproj
- deploy.bat
> Update with master

- Snowflake.Data/Snowflake.Data.csproj
MINOR: Bumped up DotNet connector MINOR version from 4.4.1 to 4.5.0
> MINOR: Bumped up DotNet connector MINOR version from 4.4.1 to 4.5.0

- Snowflake.Data/Core/RestRequester.cs
SNOW-2115047 Log http calls time
> SNOW-2115047 Log http calls time

- Snowflake.Data.Tests/IntegrationTests/SFConnectionIT.cs
- Snowflake.Data.Tests/SFBaseTest.cs
- Snowflake.Data.Tests/Snowflake.Data.Tests.csproj
Read test config from env variables
> SNOW-2122782 Read test config from env variables

- Snowflake.Data.Tests/UnitTests/Authenticator/WorkflowIdentityFederationAuthenticatorAzureTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/WorkflowIdentityFederationAuthenticatorGcpTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/WorkflowIdentityFederationAuthenticatorOidcTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/WorkloadIdentityFederationAuthenticatorAutoDetectionTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/WorkloadIdentityFederationAuthenticatorAwsTest.cs
- Snowflake.Data.Tests/UnitTests/Authenticator/WorkloadIdentityFederationAuthenticatorTest.cs
- Snowflake.Data/Core/Authenticator/WorkloadIdentityFederationAuthenticator.cs
- doc/Connecting.md
SNOW-1902246 Remove feature flag for WIF
> SNOW-1902246 Remove feature flag for WIF

- Snowflake.Data.Tests/IntegrationTests/ConnectionMultiplePoolsIT.cs
- Snowflake.Data.Tests/IntegrationTests/ConnectionPoolCommonIT.cs
- Snowflake.Data/Core/Authenticator/WorkloadIdentityFederationAuthenticator.cs
SNOW-2271316 Retry flaky tests
> SNOW-2271316 Retry flaky tests

- Snowflake.Data.Tests/UnitTests/Revocation/CertificateRevocationVerifierTest.cs
- Snowflake.Data.Tests/Util/CertificateGenerator.cs
- Snowflake.Data/Core/Revocation/CertificateRevocationVerifier.cs
SNOW-2117149 handle short lived certificates
> SNOW-2117149 handle short lived certificates

- Snowflake.Data.Tests/UnitTests/Revocation/CertificateCrlDistributionPointsExtractorTest.cs
- Snowflake.Data.Tests/UnitTests/Revocation/CertificateRevocationVerifierTest.cs
- Snowflake.Data.Tests/Util/CertificateGenerator.cs
- Snowflake.Data/Core/Revocation/CertificateCrlDistributionPointsExtractor.cs
SNOW-2117149 Extract only http urls from certificate distribution points
> SNOW-2117149 Extract only http urls from certificate distribution points

- .github/workflows/changelog.yml
- CHANGELOG.md
changelog and description of the closest release
> SNOW-2337826 added changelog
